# Generated by Django 3.1.6 on 2021-02-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('buyer', models.CharField(max_length=200)),
                ('seller', models.CharField(max_length=200)),
                ('channel', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('order_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
